services:
  docker-cloudflare-ddns:
    image: ${IMAGE_NAME}
    network_mode: host
    container_name: docker-cloudflare-ddns
    ports:
      - "5055:5055"  # Webhook port for Fritzbox
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_ID=${CF_ZONE_ID}
      - STATIC_HOSTS=${STATIC_HOSTS}
    restart: unless-stopped
